"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

const API_URL =
  "https://hchen34-creater--performance-machine-api-web.modal.run";

export default function PerformanceScorer() {
  const [horsepower, setHorsepower] = useState("650");
  const [zeroToSixty, setZeroToSixty] = useState("3.1");
  const [price, setPrice] = useState("120000");
  const [score, setScore] = useState<number | null>(null);
  const [interpretation, setInterpretation] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function analyzeVehicle() {
    setLoading(true);
    setError("");
    setScore(null);

    try {
      const response = await fetch(`${API_URL}/score`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          horsepower: Number(horsepower),
          zero_to_sixty: Number(zeroToSixty),
          price: Number(price),
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error("The vehicle values were not accepted by the API.");
      }

      setScore(data.anomaly_distance);
      setInterpretation(data.interpretation);
    } catch {
      setError("Unable to reach the performance API.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card className="border-zinc-800 bg-zinc-900/60">
      <CardHeader>
        <CardTitle className="text-white">
          Performance Profile Analyzer
        </CardTitle>

        <CardDescription>
          Enter a vehicle&apos;s specifications to compare it with the fitted
          performance-car reference data.
        </CardDescription>
      </CardHeader>

      <CardContent>
        <div className="grid gap-4 md:grid-cols-3">
          <div>
            <label className="mb-2 block text-sm text-zinc-400">
              Horsepower
            </label>
            <input
              type="number"
              value={horsepower}
              onChange={(e) => setHorsepower(e.target.value)}
              className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"
            />
          </div>

          <div>
            <label className="mb-2 block text-sm text-zinc-400">
              0–60 Time (seconds)
            </label>
            <input
              type="number"
              step="0.1"
              value={zeroToSixty}
              onChange={(e) => setZeroToSixty(e.target.value)}
              className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"
            />
          </div>

          <div>
            <label className="mb-2 block text-sm text-zinc-400">
              Price ($)
            </label>
            <input
              type="number"
              value={price}
              onChange={(e) => setPrice(e.target.value)}
              className="w-full rounded-md border border-zinc-700 bg-zinc-950 px-3 py-2 text-white"
            />
          </div>
        </div>

        <Button
          onClick={analyzeVehicle}
          disabled={loading}
          className="mt-5"
        >
          {loading ? "Analyzing..." : "Analyze Vehicle"}
        </Button>

        {score !== null && (
          <div className="mt-6 rounded-lg border border-zinc-800 bg-zinc-950 p-5">
            <p className="text-xs font-semibold uppercase tracking-widest text-zinc-500">
              Anomaly Distance
            </p>

            <p className="mt-1 text-3xl font-bold text-red-500">
              {score.toFixed(3)}
            </p>

            <p className="mt-2 text-sm text-zinc-400">
              {interpretation}
            </p>

            <p className="mt-3 text-xs text-zinc-600">
              Result generated by the deployed Modal API.
            </p>
          </div>
        )}

        {error && (
          <p className="mt-4 text-sm text-red-500">
            {error}
          </p>
        )}
      </CardContent>
    </Card>
  );
}